#!/bin/bash

# This script is for use with Linux/macOS/Unix.
# It was auto-generated by near-workspaces-ava,
cd tests-ava
npm install
npm run test -- $@ # pass along any CLI flags, such as `--verbose`